services:
  postgres:
    image: postgres:15-alpine
    container_name: mithril-postgres
    environment:
      POSTGRES_USER: mithril
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: mithril
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./internal/database/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mithril"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mithril-network

  # # redis:
  # #   image: redis:7-alpine
  # #   container_name: mithril-redis
  # #   ports:
  # #     - "6379:6379"
  # #   healthcheck:
  # #     test: ["CMD", "redis-cli", "ping"]
  # #     interval: 10s
  # #     timeout: 5s
  # #     retries: 5
  # #   networks:
  # #     - mithril-network

  nats:
    image: nats:latest
    ports:
      - "4222:4222"
    networks:
      - mithril-network

  # # migrations:
  # #   build:
  # #     context: .
  # #     dockerfile: docker/migrations.Dockerfile
  # #   container_name: mithril-migrations
  # #   environment:
  # #     DATABASE_URL: "postgres://mithril:dev_password@postgres:5432/mithril"
  # #   depends_on:
  # #     postgres:
  # #       condition: service_healthy
  # #   networks:
  # #     - mithril-network


  api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    container_name: mithril-api
    environment:
      DATABASE_URL: "postgres://mithril:dev_password@postgres:5432/mithril"
      REDIS_URL: "redis://redis:6379"
      NATS_URL: "nats://nats:4222"
      API_42_UID: ${CLIENT_42_ID}
      API_42_SEC: ${CLIENT_42_SECRET}
      CALL_BACK: "http://10.11.2.2:8080/callback"
      LOG_LEVEL: "debug"
      DB_HOST: "mithril-postgres"
      DB_USER: "mithril"
      DB_PASSWORD: "dev_password"
      DB_NAME: "mithril"
      DB_PORT: "5432"
      PORT: "3000"
    ports:
      - "3000:3000"
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      nats:
        condition: service_started
      # redis:
      #   condition: service_healthy
      # migrations:
      #   condition: service_completed_successfully
    networks:
      - mithril-network
    restart: unless-stopped

  grading:
    build:
      context: .
      dockerfile: docker/grading.Dockerfile
    container_name: mithril-grading
    environment:
      NATS_URL: "nats://nats:4222"
      LOG_LEVEL: "debug"
    depends_on:
      nats:
        condition: service_started
    networks:
      - mithril-network
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: docker/worker.Dockerfile
    image: mithril-worker-image:latest
    # ulimits:
    #   nproc:
    #     soft: 50
    #     hard: 100
    #   fsize: 
    #     soft: 1000000
    #     hard: 1000000
    deploy:
      # resources:
      #   limits:
      #     memory: 512M
      #     cpus: '1.0'
      replicas: 9
      restart_policy:
        condition: always
    depends_on:
      nats:
        condition: service_started
    networks:
      - mithril-network

volumes:
  postgres_data:

networks:
  mithril-network:
    driver: bridge
